### ISSUE TITLE
Seed words

### ISSUE THREAD

**Issue by masherak** [invis87/waves-seed-generator#2]
Hello, how I can change seed hash to the seed words? Thank you

**Comment by pronvis** [comment]
Hi!
2 years gone from last commit. I do not remember anything concrete about this project). Better if you do what you want by yourself, or gimme link to concrete piece of code at least

**Comment by masherak** [comment]
<img width="503" alt="image" src="https://user-images.githubusercontent.com/15813908/124104039-278af380-da62-11eb-90ae-19ed46ec746c.png">

On the image you can see output of your application - there is a seed property. But I use seeds like seed words from this source https://github.com/wavesplatform/WavesCS/blob/master/WavesCS/Resources/SeedWords.txt . I do not know how to convert this hash format of seed to seed words.

**Comment by pronvis** [comment]
There is no difference between my seed and "seed words" - they both just `input string` for function. You can use those seed without "unhashing" it. 
As far  as I remember))
Go through code and solve your "issue" by yourself please
